# Generated by Django 5.1 on 2024-08-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_brand_alter_distributor_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='No brand', max_length=100),
        ),
    ]
