# Generated by Django 5.1 on 2024-12-09 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_category_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='ref',
        ),
    ]
