version: "3.8"  

services:
  db:
    image: postgres:16.3
    container_name: postgres_db
    env_file: .env 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Backup.sql:/docker-entrypoint-initdb.d/Backup.sql 

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_web
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env 
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: .env  
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  postgres_data:
